### ISSUE TITLE
Vlab init with non-CORP domain credentials 

### ISSUE THREAD

**Issue by AndrewDashner** [willnx/vlab#15]
Attempting to init vlab will expect CORP credentials, but I'm on a domain image and not joined to the CORP domain to just enter CORP creds. I know my corp id(adashner) though. 

PS C:\Users\Andrew_Dashner> vlab --version
vlab, version 2019.03.28
PS C:\Users\Andrew_Dashner> vlab init
Please enter your CORP domain password:
Error: Invalid password supplied for user Andrew_Dashner
PS C:\Users\Andrew_Dashner>

**Comment by willnx** [comment]
Of course we have people in the _same roles_ joined to different domains... 😒 

### TL;DR
Today, run: `vlab --vlab-username adashner init`
Until I get a fix in place, run `vlab --vlab-username adashner status` at the start of your day

### Details
You can explicitly define your username like this:
```
vlab --vlab-username adashner init
```

The `--vlab-username` is an option on the `vlab` command. Because your CORP username is stored in the auth token, you should only have to supply the `--vlab-username` whenever you need a new token (roughly once a day). The rest of the CLI simply reads your username out of the token, and uses that over any supplied username _vis-a-vis_ the CLI.

**Comment by willnx** [comment]
Turns out, the `AMER` domain is just an OU under `CORP`. After talking with @AndrewDashner, we figured out the problem was he was trying to use the password for the DESKTOP domain.
