### ISSUE TITLE
vlab should automatically delete VM should user decide to abort during VM creation

### ISSUE THREAD

**Issue by JohnVo620** [willnx/vlab#8]
```
C:\Windows\System32>vlab --version
vlab, version 0.2.7

C:\Windows\System32>vlab create onefs -i 8.0.0.6 -n jvo-8006 -x 192.168.1.9 192.168.1.9 -c 1
Deploying 1 node running 8.0.0.6
< ctrl + c after a few seconds>
Aborted!

C:\Windows\System32>vlab show onefs
Collecting information about your OneFS nodes
 Name       | IPs   | Type   | Version   | Powered   | Console
------------+-------+--------+-----------+-----------+-----------------------------------------------------------------------
<snippet>
 jvo-8006-1 |       | OneFS  | 8.0.0.6   | On        | https://vlab-dev.igs.corp/api/1/link/eb58bc3861623aaf75f25f60b195bcde
```

**Comment by willnx** [comment]
I get where you're coming from on this; most users will assume the deploy is synchronous and so jamming `ctl c` would stop the process and _unwind_ the state. However, interacting with infrastructure is entirely asynchronous, and pressing `ctl c` will almost always interrupt the _"is it done yet"_ logic of the CLI. This is why pressing `ctl c` after the deploy _gets going_ results with the VM still being created. Interacting with the infrastructure must always be async because deploying an OVA exceeds HTTP timeouts for request/response.

The server-side logic for anything under `/api/<version>/inf` is something like this:

![image](https://user-images.githubusercontent.com/12264343/50920898-73adcd80-13fb-11e9-956d-51c74aecd20f.png)


The thing to keep at the front of your brain when looking at that diagram is that each line represents a separate process as time progresses (downwards). The arrows are, for lack of a better word, messages being exchanged between the given processes.

The main reason I took time to create this diagram is to help illustrate how this enhancement will not be trivial to implement, even though it's a very fair and reasonable request.

**Comment by willnx** [comment]
backlogging this request. It's a good request, but I'm just not ready to add this level of complexity to vLab.
